import { createSlice, createAsyncThunk, PayloadAction } from '@reduxjs/toolkit'
import { invoke } from '@tauri-apps/api/core'
import { settingsStore } from '../../store/settings'
import { VaultContent, Entry, DataEntry, GroupEntry } from '../../interfaces/vault.interface'

export interface Vault {
  id: string
  name: string
  path: string
  lastAccessed?: string // Always store as ISO string for serialization
  isLocked: boolean
  // In-memory data
  data?: {
    credential?: string
    content?: VaultContent
    navigationPath?: string
  }
}

// Types for vault entry operations - using the new unified structure
export type VaultEntry = DataEntry
export type VaultGroup = GroupEntry

interface VaultState {
  savedVaults: Vault[]
  currentVault: Vault | null
  loading: boolean
  error: string | null
  // Unified vault state with single entries array
  vaultState: {
    isLocked: boolean
    encryptedData?: string // Never persisted
    entries: Entry[] // Unified array containing both DataEntry and GroupEntry
  }
}

// Helper function to save vault state to settings store
const saveVaultStateToSettings = async (state: VaultState) => {
  try {
    // Only save 
    await settingsStore.set('vaults', state.savedVaults)
  } catch (error) {
    console.error('Failed to save vault state to settings:', error)
  }
}

// Helper function to load vault state from settings store
export const loadVaultStateFromSettings = async (): Promise<Partial<VaultState>> => {
  try {
    const savedVaults = await settingsStore.get('vaults')
    if (savedVaults && Array.isArray(savedVaults)) {
      // Process the saved vaults array
      const processedState = {
        savedVaults: savedVaults.map((vault: any) => ({
          ...vault,
          lastAccessed: vault.lastAccessed || undefined, // Keep as string
          isLocked: true // Always start locked
        })),
        currentVault: null, // Never restore current vault for security
      }
      return processedState
    }
  } catch (error) {
    console.error('Failed to load vault state from settings:', error)
  }
  return {}
}

// Action Types
export const SET_VAULT_STATE = 'vault/setVaultState'
export const ADD_VAULT_ENTRY = 'vault/addVaultEntry'
export const ADD_VAULT_GROUP = 'vault/addVaultGroup'
export const UPDATE_ENCRYPTED_VAULT = 'vault/updateEncryptedVault'

// Async Thunks
export const unlockVault = createAsyncThunk<
  VaultContent,
  { password: string; filePath: string },
  { rejectValue: string }
>(
  'vault/unlockVault',
  async ({ password, filePath }, { rejectWithValue }) => {
    try {
      const vaultData = await invoke<VaultContent>('unlock_vault', {
        password,
        path: filePath
      })
      return vaultData
    } catch (error) {
      return rejectWithValue(error as string)
    }
  }
)

export const addVaultEntry = createAsyncThunk<
  DataEntry,
  VaultEntry,
  { rejectValue: string }
>(
  'vault/addVaultEntry',
  async (entry, { rejectWithValue }) => {
    try {
      // Add entry to local state (will be saved via saveVault)
      return entry
    } catch (error) {
      return rejectWithValue(error as string)
    }
  }
)

export const addVaultGroup = createAsyncThunk<
  GroupEntry,
  VaultGroup,
  { rejectValue: string }
>(
  'vault/addVaultGroup',
  async (group, { rejectWithValue }) => {
    try {
      // Validate group data
      if (!group.id || !group.name.trim() || group.entry_type !== 'group') {
        throw new Error('Invalid group data')
      }
      
      // Add group to local state (will be saved via auto-save effect)
      return group
    } catch (error) {
      return rejectWithValue(error as string)
    }
  }
)

export const saveVault = createAsyncThunk<
  void,
  { filePath: string; password: string },
  { rejectValue: string; state: { vault: VaultState } }
>(
  'vault/saveVault',
  async ({ filePath, password }, { getState, rejectWithValue }) => {
    try {
      const state = getState()
      const { entries } = state.vault.vaultState
      
      const vaultContent: VaultContent = {
        updated_at: new Date().toISOString(),
        hmac: '', // Will be generated by Tauri
        entries: entries
      }
      
      await invoke('update_vault', {
        filePath,
        password,
        vaultContent
      })
    } catch (error) {
      return rejectWithValue(error as string)
    }
  }
)

const initialState: VaultState = {
  savedVaults: [],
  currentVault: null,
  loading: false,
  error: null,
  vaultState: {
    isLocked: true,
    entries: [] // Unified array for both entries and groups
  }
}

export const vaultSlice = createSlice({
  name: 'vault',
  initialState,
  reducers: {
    addVault: (state, action: PayloadAction<Vault>) => {
      state.savedVaults.push(action.payload)
      // Save to settings store asynchronously
      saveVaultStateToSettings(state)
    },
    removeVault: (state, action: PayloadAction<string>) => {
      state.savedVaults = state.savedVaults.filter(vault => vault.id !== action.payload)
      // Save to settings store asynchronously
      saveVaultStateToSettings(state)
    },
    updateVault: (state, action: PayloadAction<Vault>) => {
      const index = state.savedVaults.findIndex(vault => vault.id === action.payload.id)
      if (index !== -1) {
        state.savedVaults[index] = action.payload
      }
      // Save to settings store asynchronously
      saveVaultStateToSettings(state)
    },
    setCurrentVault: (state, action: PayloadAction<Vault | null>) => {
      state.currentVault = action.payload
      // Save to settings store asynchronously
      saveVaultStateToSettings(state)
    },
    updateLastAccessed: (state, action: PayloadAction<string>) => {
      const vault = state.savedVaults.find(vault => vault.id === action.payload)
      if (vault) {
        vault.lastAccessed = new Date().toISOString()
      }
      // Save to settings store asynchronously
      saveVaultStateToSettings(state)
    },
    setLoading: (state, action: PayloadAction<boolean>) => {
      state.loading = action.payload
      // Don't save loading state to persistent storage
    },
    setError: (state, action: PayloadAction<string | null>) => {
      state.error = action.payload
      // Don't save error state to persistent storage
    },
    clearError: (state) => {
      state.error = null
      // Don't save error state to persistent storage
    },
    // New action to restore state from settings
    restoreVaultState: (state, action: PayloadAction<Partial<VaultState>>) => {
      const { savedVaults, currentVault } = action.payload
      if (savedVaults) {
        state.savedVaults = savedVaults
      }
      if (currentVault !== undefined) {
        state.currentVault = currentVault
      }
    },
    // New synchronous actions for vault state management
    setVaultState: (state, action: PayloadAction<{ isLocked: boolean; entries: Entry[] }>) => {
      state.vaultState.isLocked = action.payload.isLocked
      state.vaultState.entries = action.payload.entries
      // Don't persist encrypted data
    },
    lockVault: (state) => {
      state.vaultState.isLocked = true
      state.vaultState.entries = []
      state.vaultState.encryptedData = undefined
      // Don't persist when locking
    },
    updateEncryptedVault: (state, action: PayloadAction<string>) => {
      state.vaultState.encryptedData = action.payload
      // This data should never be persisted
    },
  },
  extraReducers: (builder) => {
    builder
      // unlockVault cases
      .addCase(unlockVault.pending, (state) => {
        state.loading = true
        state.error = null
      })
      .addCase(unlockVault.fulfilled, (state, action) => {
        state.loading = false
        state.vaultState.isLocked = false
        
        // Store all entries in unified array
        state.vaultState.entries = action.payload.entries
      })
      .addCase(unlockVault.rejected, (state, action) => {
        state.loading = false
        state.error = action.payload || 'Failed to unlock vault'
        state.vaultState.isLocked = true
      })
      
      // addVaultEntry cases
      .addCase(addVaultEntry.pending, (state) => {
        state.loading = true
        state.error = null
      })
      .addCase(addVaultEntry.fulfilled, (state, action) => {
        state.loading = false
        state.vaultState.entries.push(action.payload)
      })
      .addCase(addVaultEntry.rejected, (state, action) => {
        state.loading = false
        state.error = action.payload || 'Failed to add vault entry'
      })
      
      // addVaultGroup cases
      .addCase(addVaultGroup.pending, (state) => {
        state.loading = true
        state.error = null
      })
      .addCase(addVaultGroup.fulfilled, (state, action) => {
        state.loading = false
        state.vaultState.entries.push(action.payload)
      })
      .addCase(addVaultGroup.rejected, (state, action) => {
        state.loading = false
        state.error = action.payload || 'Failed to add vault group'
      })
      
      // saveVault cases
      .addCase(saveVault.pending, (state) => {
        state.loading = true
        state.error = null
      })
      .addCase(saveVault.fulfilled, (state) => {
        state.loading = false
        // Update last accessed time for current vault
        if (state.currentVault) {
          const vault = state.savedVaults.find(v => v.id === state.currentVault!.id)
          if (vault) {
            vault.lastAccessed = new Date().toISOString()
          }
        }
      })
      .addCase(saveVault.rejected, (state, action) => {
        state.loading = false
        state.error = action.payload || 'Failed to save vault'
      })
  },
})

export const {
  addVault,
  removeVault,
  updateVault,
  setCurrentVault,
  updateLastAccessed,
  setLoading,
  setError,
  clearError,
  restoreVaultState,
  setVaultState,
  lockVault,
  updateEncryptedVault,
} = vaultSlice.actions

export default vaultSlice.reducer