import {
	createAsyncThunk,
	createSlice,
	type PayloadAction,
} from "@reduxjs/toolkit"
import type { Entry, VaultContent } from "../../interfaces/vault.interface"
import VaultCommands from "../../services/commands"
import { settingsStore } from "../../store/settings"
import { VaultUpdater } from "../../utils/VaultUpdater"
import type { RootState } from "../store"

export interface Vault {
	id: string
	name: string
	path: string
	lastAccessed?: string
	isLocked: boolean
	// Multi-vault: volatile in-memory state, not persisted
	volatile: {
		credential: string
		entries: Entry[]
		navigationPath?: string
		encryptedData?: string
	}
}

// Types for vault entry operations - using the new unified structure

export interface VaultState {
	vaults: Vault[]
	savedVaults?: Vault[] // For migration safety
	currentVaultId: string | null
	loading: boolean
	error: string | null
}

/**
 * Save vaults array to settings store.
 * Mirrors savePreferencesToSettings pattern.
 */
const saveVaultStateToSettings = async (vaults: Vault[]) => {
	try {
		const persistentVaults = vaults.map((v) => ({
			id: v.id,
			name: v.name,
			path: v.path,
			lastAccessed: v.lastAccessed,
			isLocked: v.isLocked,
		}))
		await settingsStore.set("vaults", persistentVaults)
	} catch (error) {
		console.error("Error saving vaults to settings:", error)
	}
}

/**
 * Load vault state from settings store.
 * Mirrors loadPreferencesFromSettings return type/style.
 */
export const loadVaultStateFromSettings = async (): Promise<
	Partial<VaultState>
> => {
	try {
		const vaults = await settingsStore.get("vaults")
		const savedVaults = await settingsStore.get("savedVaults")
		if (vaults && Array.isArray(vaults)) {
			return {
				vaults: vaults.map((vault: any) => ({
					...vault,
					lastAccessed: vault.lastAccessed || undefined,
					isLocked: true,
				})),
				currentVaultId: null,
			}
		} else if (savedVaults && Array.isArray(savedVaults)) {
			// Migrate legacy savedVaults to vaults
			return {
				vaults: savedVaults.map((vault: any) => ({
					...vault,
					lastAccessed: vault.lastAccessed || undefined,
					isLocked: true,
				})),
				currentVaultId: null,
			}
		} else {
			return {
				vaults: [],
				currentVaultId: null,
			}
		}
	} catch (error) {
		console.error("Error loading vaults from settings:", error)
	}
	return { vaults: [], currentVaultId: null }
}

// Action Types
export const SET_VAULT_STATE = "vault/setVaultState"

// Async Thunks
export const readVault = createAsyncThunk<
	VaultContent,
	{ password: string; filePath: string },
	{ rejectValue: string }
>("vault/readVault", async ({ password, filePath }, { rejectWithValue }) => {
	try {
		const vaultData = await VaultCommands.read(filePath, password)
		return vaultData
	} catch (error) {
		return rejectWithValue(error as string)
	}
})

/**
 * Unified reducer for batch updating vault entries.
 * Supports adds, updates, and deletes in a single action.
 */

export const saveVault = createAsyncThunk<
	void,
	{ filePath: string; password: string },
	{ rejectValue: string; state: RootState }
>(
	"vault/saveVault",
	async ({ filePath, password }, { getState, rejectWithValue }) => {
		try {
			const state = getState()
			const vault = state.vault.vaults.find(
				(v: Vault) => v.id === state.vault.currentVaultId
			)
			const entries = vault?.volatile?.entries ?? []
			const vaultContent: VaultContent = {
				updated_at: new Date().toISOString(),
				hmac: "", // Will be generated by Tauri
				entries: entries,
			}
			console.log("Saving vault content:", vaultContent)
			await VaultCommands.write(filePath, password, vaultContent)
		} catch (error) {
			return rejectWithValue(error as string)
		}
	}
)

export const addVaultEntry = createAsyncThunk<
	Entry[],
	{ parentId: string | null; newEntry: Entry },
	{ rejectValue: string; state: RootState }
>(
	"vault/addEntry",
	async (
		arg: { parentId: string | null; newEntry: Entry },
		{ getState, dispatch, rejectWithValue }
	) => {
		try {
			const state = getState() as RootState
			const vault = state.vault.vaults.find(
				(v: Vault) => v.id === state.vault.currentVaultId
			)
			const updater = new VaultUpdater(vault?.volatile?.entries ?? [])
			updater.addEntry(arg.parentId, arg.newEntry)
			const newEntries = updater.getEntries()
			dispatch(
				vaultSlice.actions.setVaultEntries({
					vaultId: state.vault.currentVaultId!,
					entries: newEntries,
				})
			)
			if (!vault?.volatile?.credential) {
				throw new Error("No current vault or credential available")
			}
			await dispatch(
				saveVault({
					filePath: vault.path,
					password: vault.volatile.credential,
				})
			).unwrap()
			return newEntries
		} catch (error) {
			return rejectWithValue((error as Error).message)
		}
	}
)

export const updateVaultEntry = createAsyncThunk<
	Entry[],
	{ entryId: string; updates: Partial<Entry> },
	{ rejectValue: string; state: RootState }
>(
	"vault/updateEntry",
	async (
		arg: { entryId: string; updates: Partial<Entry> },
		{ getState, dispatch, rejectWithValue }
	) => {
		try {
			const state = getState() as RootState
			const vault = state.vault.vaults.find(
				(v: Vault) => v.id === state.vault.currentVaultId
			)
			const updater = new VaultUpdater(vault?.volatile?.entries ?? [])
			updater.updateEntry(arg.entryId, arg.updates)
			const newEntries = updater.getEntries()
			dispatch(
				vaultSlice.actions.setVaultEntries({
					vaultId: state.vault.currentVaultId!,
					entries: newEntries,
				})
			)
			if (!vault?.volatile?.credential) {
				throw new Error("No current vault or credential available")
			}
			await dispatch(
				saveVault({
					filePath: vault.path,
					password: vault.volatile.credential,
				})
			).unwrap()
			return newEntries
		} catch (error) {
			return rejectWithValue((error as Error).message)
		}
	}
)

export const deleteVaultEntry = createAsyncThunk<
	Entry[],
	string,
	{ rejectValue: string; state: RootState }
>(
	"vault/deleteEntry",
	async (entryId: string, { getState, dispatch, rejectWithValue }) => {
		try {
			const state = getState() as RootState
			const vault = state.vault.vaults.find(
				(v: Vault) => v.id === state.vault.currentVaultId
			)
			const updater = new VaultUpdater(vault?.volatile?.entries ?? [])
			updater.deleteEntry(entryId)
			const newEntries = updater.getEntries()
			dispatch(
				vaultSlice.actions.setVaultEntries({
					vaultId: state.vault.currentVaultId!,
					entries: newEntries,
				})
			)
			if (!vault?.volatile?.credential) {
				throw new Error("No current vault or credential available")
			}
			await dispatch(
				saveVault({
					filePath: vault.path,
					password: vault.volatile.credential,
				})
			).unwrap()
			return newEntries
		} catch (error) {
			return rejectWithValue((error as Error).message)
		}
	}
)

const initialState: VaultState = {
	vaults: [],
	savedVaults: [],
	currentVaultId: null,
	loading: false,
	error: null,
}

export const vaultSlice = createSlice({
	name: "vault",
	initialState,
	reducers: {
		addVault: (state, action: PayloadAction<Vault>) => {
			const vault = {
				...action.payload,
				volatile: {
					entries: [],
					credential: "",
					navigationPath: "/",
					encryptedData: undefined,
				},
			}
			state.vaults.push(vault)
			void saveVaultStateToSettings(state.vaults)
		},
		removeVault: (state, action: PayloadAction<string>) => {
			state.vaults = state.vaults.filter(
				(vault: Vault) => vault.id !== action.payload
			)
			void saveVaultStateToSettings(state.vaults)
			if (state.currentVaultId === action.payload) {
				state.currentVaultId = null
			}
		},
		updateVault: (state, action: PayloadAction<Vault>) => {
			const index = state.vaults.findIndex(
				(vault: Vault) => vault.id === action.payload.id
			)
			if (index !== -1) {
				state.vaults[index] = action.payload
			}
			void saveVaultStateToSettings(state.vaults)
		},
		setCurrentVault: (state, action: PayloadAction<string | null>) => {
			state.currentVaultId = action.payload
		},
		updateLastAccessed: (state, action: PayloadAction<string>) => {
			const vault = state.vaults.find(
				(vault: Vault) => vault.id === action.payload
			)
			if (vault) {
				vault.lastAccessed = new Date().toISOString()
			}
			void saveVaultStateToSettings(state.vaults)
		},
		setLoading: (state, action: PayloadAction<boolean>) => {
			state.loading = action.payload
		},
		setError: (state, action: PayloadAction<string | null>) => {
			state.error = action.payload
		},
		clearError: (state) => {
			state.error = null
		},
		restoreVaultState: (
			state,
			action: PayloadAction<Partial<VaultState>>
		) => {
			if (action.payload.vaults && Array.isArray(action.payload.vaults)) {
				state.vaults = action.payload.vaults
			} else if (action.payload.savedVaults && Array.isArray(action.payload.savedVaults)) {
				// Migration: handle legacy savedVaults
				state.vaults = action.payload.savedVaults
			} else {
				state.vaults = []
			}
			state.currentVaultId = null
		},
		setVaultCredential: (
			state,
			action: PayloadAction<{ vaultId: string; credential: string }>
		) => {
			const vault = state.vaults.find(
				(v) => v.id === action.payload.vaultId
			)
			if (vault) {
				if (!vault.volatile) {
					vault.volatile = {
						entries: [],
						credential: "",
						navigationPath: "/",
						encryptedData: undefined,
					}
				}
				vault.volatile.credential = action.payload.credential
			}
		},
		setNavigationPath: (
			state,
			action: PayloadAction<{ vaultId: string; navigationPath: string }>
		) => {
			const vault = Array.isArray(state.vaults)
				? state.vaults.find((v) => v.id === action.payload.vaultId)
				: undefined
			if (vault) {
				if (!vault.volatile) {
					vault.volatile = {
						entries: [],
						credential: "",
						navigationPath: "/",
						encryptedData: undefined,
					}
				}
				vault.volatile.navigationPath = action.payload.navigationPath
			}
		},
		setVaultEntries: (
			state,
			action: PayloadAction<{ vaultId: string; entries: Entry[] }>
		) => {
			const vault = Array.isArray(state.vaults)
				? state.vaults.find((v) => v.id === action.payload.vaultId)
				: undefined
			if (vault) {
				if (!vault.volatile) {
					vault.volatile = {
						entries: [],
						credential: "",
						navigationPath: "/",
						encryptedData: undefined,
					}
				}
				vault.volatile.entries = action.payload.entries
			}
		},
		lockVault: (state, action: PayloadAction<string>) => {
			const vault = state.vaults.find((v) => v.id === action.payload)
			if (vault && vault.volatile) {
				vault.volatile.entries = []
				vault.volatile.encryptedData = undefined
				vault.isLocked = true
				vault.volatile.credential = "" // Clear credential on lock
				vault.volatile.navigationPath = "/"
			}
		},
	},
	extraReducers: (builder) => {
		builder
			// readVault cases
			.addCase(readVault.pending, (state) => {
				state.loading = true
				state.error = null
			})
			.addCase(readVault.fulfilled, (state, action) => {
				state.loading = false
				if (state.currentVaultId) {
					const vault = state.vaults.find(
						(v) => v.id === state.currentVaultId
					)
					if (vault) {
						if (!vault.volatile) {
							vault.volatile = {
								entries: [],
								credential: "",
								navigationPath: "/",
								encryptedData: undefined,
							}
						}
						vault.isLocked = false
						vault.volatile.entries = action.payload.entries
					}
				}
			})
			.addCase(readVault.rejected, (state, action) => {
				state.loading = false
				state.error = action.payload || "Failed to read vault"
				if (state.currentVaultId) {
					const vault = state.vaults.find(
						(v) => v.id === state.currentVaultId
					)
					if (vault) {
						vault.isLocked = true
					}
				}
			})
			// saveVault cases
			.addCase(saveVault.pending, (state) => {
				state.loading = true
				state.error = null
			})
			.addCase(saveVault.fulfilled, (state) => {
				state.loading = false
				if (state.currentVaultId) {
					const vault = state.vaults.find(
						(v) => v.id === state.currentVaultId
					)
					if (vault) {
						vault.lastAccessed = new Date().toISOString()
					}
				}
			})
			.addCase(saveVault.rejected, (state, action) => {
				state.loading = false
				state.error = action.payload || "Failed to save vault"
			})
			// New cases for addVaultEntry
			.addCase(addVaultEntry.pending, (state) => {
				state.loading = true
				state.error = null
			})
			.addCase(addVaultEntry.fulfilled, (state) => {
				state.loading = false
			})
			.addCase(addVaultEntry.rejected, (state, action) => {
				state.loading = false
				state.error = action.payload ?? "Failed to add entry"
			})
			// New cases for updateVaultEntry
			.addCase(updateVaultEntry.pending, (state) => {
				state.loading = true
				state.error = null
			})
			.addCase(updateVaultEntry.fulfilled, (state) => {
				state.loading = false
			})
			.addCase(updateVaultEntry.rejected, (state, action) => {
				state.loading = false
				state.error = action.payload ?? "Failed to update entry"
			})
			// New cases for deleteVaultEntry
			.addCase(deleteVaultEntry.pending, (state) => {
				state.loading = true
				state.error = null
			})
			.addCase(deleteVaultEntry.fulfilled, (state) => {
				state.loading = false
			})
			.addCase(deleteVaultEntry.rejected, (state, action) => {
				state.loading = false
				state.error = action.payload ?? "Failed to delete entry"
			})
	},
})

export const {
	addVault,
	removeVault,
	updateVault,
	setCurrentVault,
	updateLastAccessed,
	setLoading,
	setError,
	clearError,
	restoreVaultState,
	lockVault,
	setVaultCredential,
	setNavigationPath,
	setVaultEntries,
} = vaultSlice.actions

export default vaultSlice.reducer
