#[cfg(test)]
mod tests {
    use crate::crypto::random::{generate_random_bytes, generate_salt, generate_key, generate_nonce};
    use crate::crypto::constants::{SALT_LEN, KEY_LEN, NONCE_LEN};

    #[test]
    fn test_generate_random_bytes() {
        // Test generating bytes of a specific length
        let len = 32;
        let bytes = generate_random_bytes(len).expect("Failed to generate random bytes");
        assert_eq!(bytes.len(), len);

        // Test generating bytes of a different length
        let len = 16;
        let bytes = generate_random_bytes(len).expect("Failed to generate random bytes");
        assert_eq!(bytes.len(), len);

        // Test generating zero bytes
        let len = 0;
        let bytes = generate_random_bytes(len).expect("Failed to generate random bytes");
        assert_eq!(bytes.len(), len);

        // Test that generated bytes are likely random (basic check)
        let len = 64;
        let bytes1 = generate_random_bytes(len).expect("Failed to generate random bytes");
        let bytes2 = generate_random_bytes(len).expect("Failed to generate random bytes");
        assert_ne!(bytes1, bytes2, "Generated bytes should be different");
    }

    #[test]
    fn test_generate_salt() {
        let salt = generate_salt().expect("Failed to generate salt");
        assert_eq!(salt.len(), SALT_LEN);
    }

    #[test]
    fn test_generate_key() {
        let key = generate_key().expect("Failed to generate key");
        assert_eq!(key.len(), KEY_LEN);
    }

    #[test]
    fn test_generate_nonce() {
        let nonce = generate_nonce().expect("Failed to generate nonce");
        assert_eq!(nonce.len(), NONCE_LEN);
    }
}