/**
 * Decorative vault-window mockup shown in the hero.
 * Folder and entry names are localized so the screenshot-like panel reads in the
 * visitor's language; the values are short by design (the panel is ~22rem wide).
 */

export const MOCK = {
	en: {
		alt: "The Monark vault window: a folder sidebar beside a list of entries for Google, AWS, Fastmail, GitHub and a bank account.",
		window: "Monark — Personal vault",
		sideLabel: "Folders",
		title: "Personal",
		count: "24 items",
		folders: ["All items", "Personal", "Work", "Finance", "Servers"],
		entries: [
			["G", "Google", "you@example.com", "2FA"],
			["A", "AWS", "root · us-east-1", ""],
			["F", "Fastmail", "you@example.com", "2FA"],
			["G", "GitHub", "you · SSH key", ""],
			["B", "Bank", "card + account", ""],
		],
		foot: "Locked with your master passphrase",
	},
	es: {
		alt: "La ventana de la bóveda de Monark: una barra de carpetas junto a una lista de entradas de Google, AWS, Fastmail, GitHub y un banco.",
		window: "Monark — Bóveda personal",
		sideLabel: "Carpetas",
		title: "Personal",
		count: "24 elementos",
		folders: ["Todos", "Personal", "Trabajo", "Finanzas", "Servidores"],
		entries: [
			["G", "Google", "tu@ejemplo.com", "2FA"],
			["A", "AWS", "root · us-east-1", ""],
			["F", "Fastmail", "tu@ejemplo.com", "2FA"],
			["G", "GitHub", "tú · clave SSH", ""],
			["B", "Banco", "tarjeta + cuenta", ""],
		],
		foot: "Cerrada con tu frase maestra",
	},
	pt: {
		alt: "A janela do cofre do Monark: uma barra de pastas ao lado de uma lista de itens de Google, AWS, Fastmail, GitHub e um banco.",
		window: "Monark — Cofre pessoal",
		sideLabel: "Pastas",
		title: "Pessoal",
		count: "24 itens",
		folders: ["Todos", "Pessoal", "Trabalho", "Finanças", "Servidores"],
		entries: [
			["G", "Google", "voce@exemplo.com", "2FA"],
			["A", "AWS", "root · us-east-1", ""],
			["F", "Fastmail", "voce@exemplo.com", "2FA"],
			["G", "GitHub", "você · chave SSH", ""],
			["B", "Banco", "cartão + conta", ""],
		],
		foot: "Trancado com sua frase mestra",
	},
	fr: {
		alt: "La fenêtre du coffre Monark : une barre de dossiers à côté d'une liste d'entrées Google, AWS, Fastmail, GitHub et une banque.",
		window: "Monark — Coffre personnel",
		sideLabel: "Dossiers",
		title: "Personnel",
		count: "24 éléments",
		folders: ["Tout", "Personnel", "Travail", "Finances", "Serveurs"],
		entries: [
			["G", "Google", "vous@exemple.com", "2FA"],
			["A", "AWS", "root · us-east-1", ""],
			["F", "Fastmail", "vous@exemple.com", "2FA"],
			["G", "GitHub", "vous · clé SSH", ""],
			["B", "Banque", "carte + compte", ""],
		],
		foot: "Verrouillé par votre phrase maîtresse",
	},
	de: {
		alt: "Das Tresorfenster von Monark: eine Ordnerleiste neben einer Liste mit Einträgen für Google, AWS, Fastmail, GitHub und eine Bank.",
		window: "Monark — Persönlicher Tresor",
		sideLabel: "Ordner",
		title: "Persönlich",
		count: "24 Einträge",
		folders: ["Alle", "Persönlich", "Arbeit", "Finanzen", "Server"],
		entries: [
			["G", "Google", "sie@beispiel.de", "2FA"],
			["A", "AWS", "root · us-east-1", ""],
			["F", "Fastmail", "sie@beispiel.de", "2FA"],
			["G", "GitHub", "du · SSH-Schlüssel", ""],
			["B", "Bank", "Karte + Konto", ""],
		],
		foot: "Gesichert mit Ihrer Master-Passphrase",
	},
	zh: {
		alt: "Monark 保险库窗口：左侧为文件夹栏，右侧为 Google、AWS、Fastmail、GitHub 和银行账户的条目列表。",
		window: "Monark — 个人保险库",
		sideLabel: "文件夹",
		title: "个人",
		count: "24 个项目",
		folders: ["全部", "个人", "工作", "财务", "服务器"],
		entries: [
			["G", "Google", "you@example.com", "2FA"],
			["A", "AWS", "root · us-east-1", ""],
			["F", "Fastmail", "you@example.com", "2FA"],
			["G", "GitHub", "账号 · SSH 密钥", ""],
			["B", "银行", "银行卡 + 账号", ""],
		],
		foot: "由你的主密码短语加密",
	},
	ja: {
		alt: "Monark のボルト画面：フォルダ一覧のサイドバーと、Google、AWS、Fastmail、GitHub、銀行の項目リスト。",
		window: "Monark — 個人用ボルト",
		sideLabel: "フォルダ",
		title: "個人",
		count: "24 件",
		folders: ["すべて", "個人", "仕事", "金融", "サーバー"],
		entries: [
			["G", "Google", "you@example.com", "2FA"],
			["A", "AWS", "root · us-east-1", ""],
			["F", "Fastmail", "you@example.com", "2FA"],
			["G", "GitHub", "アカウント · SSH 鍵", ""],
			["B", "銀行", "カード + 口座", ""],
		],
		foot: "マスターパスフレーズで施錠",
	},
};